// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS_lTSneel3geXrNyXerrp4Lz2vMIFRUU',
    appId: '1:860612983796:web:619188ed5e121e6e8717a1',
    messagingSenderId: '860612983796',
    projectId: 'cameye-31121',
    authDomain: 'cameye-31121.firebaseapp.com',
    storageBucket: 'cameye-31121.appspot.com',
    measurementId: 'G-CE8MVFL2MF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5gEuwEdDsX5mdvQZjMG2lna7ROaf8aJ8',
    appId: '1:860612983796:android:79607953558874df8717a1',
    messagingSenderId: '860612983796',
    projectId: 'cameye-31121',
    storageBucket: 'cameye-31121.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC9ydNpU39EA9VvumGA0ss55LoGJuHbf0',
    appId: '1:860612983796:ios:4161c56e69963af38717a1',
    messagingSenderId: '860612983796',
    projectId: 'cameye-31121',
    storageBucket: 'cameye-31121.appspot.com',
    iosBundleId: 'com.example.cameye',
);
}
